resources:
- name: cf-concourse
  type: git
  source:
    uri: https://github.com/axelaris/cf-concourse.git

jobs:
- name: deploy-vault
  plan:
  - get: cf-concourse
  - task: deploy-vault
    config:
      platform: linux
      image_resource: &common-image-resource
        type: docker-image
        source:
          repository: baber/cfbosh
      run:
        path: cf-concourse/vault/deploy-vault.sh
      params:
        BOSH_CA_CERT: {{bosh-ca-cert}}
        BOSH_ENVIRONMENT: {{bosh-env}}
        BOSH_CLIENT: {{bosh-user}}
        BOSH_CLIENT_SECRET: {{bosh-pass}}
      inputs:
        - name: cf-concourse

- name: unseal-vault
  plan:
  - get: cf-concourse
    passed: [deploy-vault]
  - task: unseal-vault
    config:
      platform: linux
      image_resource: *common-image-resource
      run:
        path: cf-concourse/vault/unseal-vault.sh
      params:
        BOSH_CA_CERT: {{bosh-ca-cert}}
        BOSH_ENVIRONMENT: {{bosh-env}}
        BOSH_CLIENT: {{bosh-user}}
        BOSH_CLIENT_SECRET: {{bosh-pass}}
      inputs:
        - name: cf-concourse
