resources:
- name: cf-concourse
  type: git
  source:
    uri: https://github.com/axelaris/cf-concourse

- name: auto
  type: concourse-version-resource

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment

- name: vault-boshrelease
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/vault-boshrelease

resource_types:
- name: concourse-version-resource
  type: docker-image
  source:
    repository: meteogroup/concourse-version-resource

jobs:

- name: vault
  plan:
  - get: auto
  - get: cf-concourse
  - get: vault-boshrelease
  - task: deploy-vault
    config:
      platform: linux
      image_resource: &common-image-resource
        type: docker-image
        source:
          repository: baber/cfbosh
          tag: cert
      run:
        path: cf-concourse/vault/deploy-vault.sh
      params:
        BOSH_CA_CERT: {{bosh-ca-cert}}
        BOSH_ENVIRONMENT: {{bosh-env}}
        BOSH_CLIENT: {{bosh-user}}
        BOSH_CLIENT_SECRET: {{bosh-pass}}
      inputs:
        - name: cf-concourse
        - name: vault-boshrelease
      outputs:
        - name: vault
  - task: unseal-vault
    config:
      platform: linux
      image_resource: *common-image-resource
      run:
        path: cf-concourse/vault/unseal-vault.sh
      inputs:
        - name: cf-concourse
        - name: vault
      outputs:
        - name: keys
  - task: update-concourse
    config:
      platform: linux
      image_resource: *common-image-resource
      run:
        path: cf-concourse/concourse/update-concourse.sh
      params:
        BOSH_CA_CERT: {{bosh-ca-cert}}
        BOSH_ENVIRONMENT: {{bosh-env}}
        BOSH_CLIENT: {{bosh-user}}
        BOSH_CLIENT_SECRET: {{bosh-pass}}
        CI_PASS: {{ci-pass}}
      inputs:
        - name: cf-concourse
        - name: keys
  - put: auto

- name: CF
  plan:
  - get: cf-concourse
  - get: auto
    passed: [vault]
    trigger: true
  - get: cf-deployment
  - task: deploy-cf
    config:
      platform: linux
      image_resource: &common-image-resource
        type: docker-image
        source:
          repository: baber/cfbosh
      run:
        path: cf-concourse/cf/deploy-cf.sh
      params:
        BOSH_CA_CERT: {{bosh-ca-cert}}
        BOSH_ENVIRONMENT: {{bosh-env}}
        BOSH_CLIENT: {{bosh-user}}
        BOSH_CLIENT_SECRET: {{bosh-pass}}
        DOMAIN: ((cf-domain))
        CF_TAG: ((cf-tag))
        VAULT_ADDR: ((vault-address))
        VAULT_TOKEN: ((secret-token))
      inputs:
        - name: cf-deployment
        - name: cf-concourse
