resources:
- name: cf-concourse
  type: git
  source:
    uri: https://github.com/axelaris/cf-concourse.git

- name: auto
  type: concourse-version-resource

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment

resource_types:
- name: concourse-version-resource
  type: docker-image
  source:
    repository: meteogroup/concourse-version-resource

jobs:

- name: vault
  plan:
  - get: auto
  - get: cf-concourse
  - task: deploy-vault
    config:
      platform: linux
      image_resource: &common-image-resource
        type: docker-image
        source:
          repository: baber/cfbosh
      run:
        path: cf-concourse/vault/deploy-vault.sh
      params:
        BOSH_CA_CERT: {{bosh-ca-cert}}
        BOSH_ENVIRONMENT: {{bosh-env}}
        BOSH_CLIENT: {{bosh-user}}
        BOSH_CLIENT_SECRET: {{bosh-pass}}
      inputs:
        - name: cf-concourse
  - task: unseal-vault
    config:
      platform: linux
      image_resource: *common-image-resource
      run:
        path: cf-concourse/vault/unseal-vault.sh
      params:
        BOSH_CA_CERT: {{bosh-ca-cert}}
        BOSH_ENVIRONMENT: {{bosh-env}}
        BOSH_CLIENT: {{bosh-user}}
        BOSH_CLIENT_SECRET: {{bosh-pass}}
      inputs:
        - name: cf-concourse
      outputs:
        - name: keys
  - task: update-concourse
    config:
      platform: linux
      image_resource: *common-image-resource
      run:
        path: cf-concourse/concourse/deploy-concourse.sh
      params:
        BOSH_CA_CERT: {{bosh-ca-cert}}
        BOSH_ENVIRONMENT: {{bosh-env}}
        BOSH_CLIENT: {{bosh-user}}
        BOSH_CLIENT_SECRET: {{bosh-pass}}
      inputs:
        - name: cf-concourse
        - name: keys
  - put: auto

- name: deploy-cf
  plan:
  - get: cf-concourse
  - get: auto
    passed: [vault]
    trigger: true
  - get: cf-deployment
  - task: deploy-cf
    config:
      platform: linux
      image_resource: &common-image-resource
        type: docker-image
        source:
          repository: baber/cfbosh
      run:
        path: cf-concourse/cf/deploy-cf.sh
      params:
        BOSH_CA_CERT: {{bosh-ca-cert}}
        BOSH_ENVIRONMENT: {{bosh-env}}
        BOSH_CLIENT: {{bosh-user}}
        BOSH_CLIENT_SECRET: {{bosh-pass}}
        DOMAIN: {{cf-domain}}
        CF_TAG: {{cf-tag}}
        VAULT_ADDR: {{vault-addr}}
        VAULT_TOKEN: {{vault-token}}
      inputs:
        - name: cf-deployment
        - name: cf-concourse
